### ISSUE TITLE
Json syntax faults

### ISSUE THREAD

**Issue by mixotiko** [fortify/ssc-restapi-client#10]
Hi!
Currently, we use Fortify Software Security Center 20.2.2.0002 but some models fail when we try to parse from json to a model. Specific models which contains org.threeten.bp.OffsetDateTime class for creationDate fields in models as Project or ProjectVersion.

We've tried to add new maven dependency version 
<dependency>
    <groupId>com.fortify</groupId>
    <artifactId>ssc-restapi-client</artifactId>
    <version>21.1</version>
    <scope>compile</scope>
</dependency>

but in maven repositories still haven't.

What should we do?

**Comment by akaryakina** [comment]
Hi, we've just released 21.1 to the public maven central repository. It should be publicly available shortly. The new client will not require the ThreeTen library for date time, but rely on java8 bundled libraries instead. 21.1 will have an updated json specification, however we are aware of a couple of places that provide incorrect model description and are already being worked on for 21.2. Please, give your specific parsing errors for us to review and decide on.

**Comment by akaryakina** [comment]
Closing since we're not using threeten since 23.1
