### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by thezim** [fortify/ssc-restapi-client#3]
This library does not support specifying timeouts for HTTP requests. This causes [issues](https://github.com/jenkinsci/fortify-plugin/issues/11) with longer operations like and FPR upload operation. `okhttp` read timeout is 10s, that is far too small for large FPRs and network bandwidth variances.

Original issue: jenkinsci/fortify-plugin#11

**Comment by charlesetd** [comment]
Unless I missed something, it should be possible to [set the OkHttpClient](https://github.com/fortify/ssc-restapi-client/blob/master/src/main/java/com/fortify/ssc/restclient/ApiClient.java#L133) of an ApiClient instance to your own OkHttpClient with [the desired timeouts](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#readTimeout-java.time.Duration-). For example:

```java
final OkHttpClient httpClient = OkHttpClient.newBuilder()
    .readTimeout(Duration.ofSeconds(1L))
    .writeTimeout(Duration.ofSeconds(1L))
    .callTimeout(Duration.ofSeconds(1L))
    .connectTimeout(Duration.ofSeconds(1L))
    .build();

final ApiClient apiClient = new ApiClient();
apiClient.setHttpClient(httpClient);
...
```

**Comment by thezim** [comment]
PR #4 was submitted to do that via environment variables.

**Comment by akaryakina** [comment]
Closing this one since there original issue has been closed in the Jenkins Fortify plugin: https://github.com/jenkinsci/fortify-plugin/issues/11
