### ISSUE TITLE
Unnesessary dependency

### ISSUE THREAD

**Issue by umlublin** [fortify/ssc-restapi-client#39]
Gradle plugin (openapi-generator-gradle-plugin:5.4.0) is connected as runtime dependency, so it and it;s transitive dependencies.

Effect of this is jenkins plugin build with this library is oversized from 3MB to over 20MB, 
and causes conflict with gitlab-api plugin.

**Comment by akaryakina** [comment]
Thank you for catching this one. I merged your pull request. Would you like to have a 23.1.2 patch version or you're willing to wait for the 23.2.x release following the Fortify 23.2 SSC release (in November)?

**Comment by umlublin** [comment]
we dont use this lib directly, but as jenkins  fortify plugin, 
because of conflicting with gitlab plugin we decided to run fortify scans with scancentral-cli

**Comment by akaryakina** [comment]
Done. We've just released the 23.1.2 with the updated dependencies.
